function symThet = T(x)
%T
%    symThet = T(X)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Jan-2026 23:31:31

symThet = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;x;-x.*(x.*(4.0e+2./1.31e+2)-1.0);x.*((x.*(4.0e+2./1.31e+2)-1.0).*(x.*(8.0e+2./1.31e+2)-2.0)-1.0);-x.*(x.*(-4.0e+2./1.31e+2)+((x.*(4.0e+2./1.31e+2)-1.0).*(x.*(8.0e+2./1.31e+2)-2.0)-1.0).*(x.*(8.0e+2./1.31e+2)-2.0)+1.0)];
end
